# -*- coding: utf-8 -*-
"""
OpenBao HCL Config Generator.

Génère le fichier de configuration HCL pour OpenBao :
    - File backend (storage locale)
    - Listener TCP localhost:8200 (TLS désactivé car localhost only)

Note: disable_mlock a été supprimé — OpenBao ≥2.0 ne supporte plus ce paramètre.
      La protection mémoire est gérée au niveau OS (swap désactivé).
"""

import logging
from pathlib import Path

from ..config import get_settings

logger = logging.getLogger("mcp-vault.openbao")


def _compute_openbao_listen_addr(api_addr: str) -> str:
    from urllib.parse import urlparse
    try:
        parsed = urlparse(api_addr)
        host = parsed.hostname or "127.0.0.1"
        port = parsed.port or 8200
        return f"{host}:{port}"
    except Exception:
        return "127.0.0.1:8200"

HCL_TEMPLATE = """
# OpenBao Server Configuration — Auto-generated by MCP Vault
# ⚠️ Ne pas modifier manuellement — ce fichier est régénéré au démarrage

storage "file" {{
  path = "{data_dir}"
}}

listener "tcp" {{
  address     = "{listen_addr}"
  tls_disable = true
}}

api_addr = "{api_addr}"

# Pas besoin de l'UI OpenBao — on a notre propre console admin
ui = false
"""


def generate_hcl_config() -> str:
    """
    Génère le fichier HCL de configuration OpenBao.

    Returns:
        Chemin absolu du fichier HCL généré
    """
    settings = get_settings()
    config_dir = Path(settings.openbao_config_dir)
    config_dir.mkdir(parents=True, exist_ok=True)

    hcl_content = HCL_TEMPLATE.format(
        data_dir=settings.openbao_data_dir,
        listen_addr=_compute_openbao_listen_addr(settings.openbao_addr),
        api_addr=settings.openbao_addr,
    )

    config_path = config_dir / "server.hcl"
    config_path.write_text(hcl_content.strip())
    logger.info(f"📄 Config HCL générée : {config_path}")

    return str(config_path)
